# -*- coding: utf-8 -*-
"""Lambda Data Science Assignment 1 - Getting Started with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PKPciwI6eq-RQkr3p-yhAkqnYivrZ1Hr

# Lambda School Data Science - Getting Started with Python

Following are exercises you should complete after watching the first intro lecture. Workflow:

1. Sign in to a Google account
2. Copy the notebook (`File` -> `Save a copy in Drive`)
3. Complete the exercises! This means fill out the code cells, and run them (shift-enter or click the play button that appears when you're in one of them)
4. Take a look at your work, and write comments/add text cells as appropriate to explain
5. Make the notebook URL viewable and submit with the standup form

## Exercise 1 - A bit of Math

For these "word" problems, use Python to clearly solve them. Your code will "show your work" - use good variable names! To show your answers you should write a `print()` statement at the end.

As you work, follow the **20 minute rule** - that means if you're stuck on something for 20 minutes, you should ask a question!

### a) It's a gas

A taxi driver is calculating their profit over two weeks by adding up the fares they charge and subtracting the cost of gas. The price of gas changes over time - it was `$3.52`/gallon the first week and `$3.57`/gallon this second week. Their car gets 20 miles per gallon.

For the first week the driver had a total of 23 passengers with average `$29` fare each, and drove a total of 160 miles. For the second week they had 17 passengers with average `$30` fare each, and drove a total of 220 miles. Assume that for both weeks they purchase all the gas needed during that week (i.e. they refuel every week to maintain a constant level of gas in the tank).

Based on the above, answer the following questions:

- What is their total profit over both weeks?
- During which week was their average (mean) profit per passenger higher?
"""

def profits(week1= 3.52, week2 = 3.57):
  miles_per_gallon = 20 
  passengers_1, passengers_2 = 23, 17
  fare_1, fare_2 = 29, 30
  distance_1, distance_2 = 160, 220
  profit_1, profit_2 = (passengers_1 * fare_1)- ((distance_1/miles_per_gallon)*week1), (passengers_2* fare_2)-((distance_2/miles_per_gallon)*week2)
  mean_1, mean_2 = profit_1/passengers_1, profit_2/passengers_2 # calculating average profit per customer for week 1 and 2
  print("Week one profit is: $",profit_1, " and profit for week two is: $",profit_2, " The total profit for both weeks is: ${}".format(round(profit_1 + profit_2, 2)))
  # I use the max statement to find the highest average profit per passenger
  if max(mean_1, mean_2) == mean_1:
    print("Average profit per passenger was higher in week 1, coming in at ${} per passenger".format(round(mean_1,2)))
  else:
    print("Average profit per passenger was higher during week 2, coming in at ${} per passenger".format(round(mean_2)))
      
profits()



"""### b) Mo' money...

A cash drawer contains 160 bills, all 10s and 50s. The total value of the 10s and 50s is $1,760.

How many of each type of bill are in the drawer? You can figure this out by trial and error (or by doing algebra with pencil and paper), but try to use loops and conditionals to check a plausible possibilities and stop when you find the correct one.
"""

import random
def iterat(a = 0, b = 0):
  tot, control, bills = 0, 0, 0
  ten, fifty = list(range(176)), list(range(34))
  ten_multiplier, fifty_multiplier = 10, 50
  while control == 0:
    for a in ten:
      for b in fifty:
        random.shuffle(fifty) #randomly organise numbers in 1 to 34 and pick one number from those randoms
      random.shuffle(ten) #randomly organise numbers in 1 to 176 and pick one number from those randoms
      tot = (a*ten_multiplier) + (b* fifty_multiplier)
      bills = a + b #add both a and b to find the total number of bills we currently have
      if tot == 1760 and bills == 160:
        control = 1
        print("The total is {}, there are are {} tens, {} fifty's and a total of {} bills".format(tot,a,b, bills))
iterat()

"""## Exercise 2 - Drawing a plot

Use NumPy and Matplotlib to draw a scatterplot of uniform random `(x, y)` values all drawn from the `[0, 1]` interval. Helpful documentation:

*   https://matplotlib.org/tutorials/index.html
*   https://docs.scipy.org/doc/numpy/user/quickstart.html

Stretch goal - draw more plots! You can refer to the [Matplotlib gallery](https://matplotlib.org/gallery.html) for inspiration, but don't just reproduce something - try to apply it to your own data.

How to get data? There's *many* ways, but a good place to get started is with [sklearn.datasets](http://scikit-learn.org/stable/datasets/index.html):

```
from sklearn import datasets
dir(datasets)
```
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

x  = np.random.uniform(0,1, 30)
y  = np.random.uniform(0,1, 30)
plt.figure(figsize=(5,5))
plt.scatter(x, y, label= 'my scatter', color= 'blue')
plt.show()

"""## Exercise 3 - Writing a function
Write a function that, given a list of numbers, calculates the mean, median, and mode of those numbers. Return a dictionary with properties for the mean, median and mode. 

For example:

```
mmm_dict = meanMedianMode([1, 2, 6, 7, 8, 9, 3, 4, 5, 10, 10])
print(mmm_dict)
> {'mean': 5.909090909090909, 'median': 6, 'mode': 10}
```

There are Python standard libraries that make calculating these numbers very easy, but first try your hand at implementing it using the `reduce()` function:
"""

import numpy as np
from functools import reduce

def meanMedianMode(numbers):
    mean_num = reduce(lambda x, y: x + y, numbers) / len(numbers)
    median_num = np.median(numbers)
    mode_num = max((numbers), key = numbers.count)
    result = {'mean': mean_num, 'median': median_num, 'mode':mode_num}
    return result
  
meanMedianMode([2,3,4,4,5,2,43,2,3,4])